/* Autogenerated file, don't edit */
/* AUTOGENERATE: src/bl/base/alnls/array_linked_list_u16_basic.c */
/*---------------------------------------------------------------------------*/

#include <bl/base/impl/array_linked_list_u16.h>

BL_EXPORT void alnls_u16_init_impl(
  alnls_u16* l, u16* nodes, uword nodes_capacity
  )
{
  l->nodes    = nodes;
  l->capacity = nodes_capacity;
  l->head     = l->capacity;
  for (alnls_u16_it it = 0; it < l->capacity; ++it) {
    alnls_u16_node_release (l, it);
  }
  l->size = 0;
}
/*---------------------------------------------------------------------------*/
BL_EXPORT alnls_u16_it alnls_u16_try_acquire_node (alnls_u16* l, alnls_u16_it n)
{
  if (alnls_u16_node_is_free (l, n)) {
    alnls_u16_acquire_node_unsafe (l, n);
    return n;
  }
  return alnls_u16_it_end (l);
}
/*---------------------------------------------------------------------------*/
BL_EXPORT alnls_u16_it alnls_u16_try_acquire_a_node (alnls_u16* l)
{
  alnls_u16_it i;
  for (i = 0; i < alnls_u16_it_end (l); ++i) {
    if (alnls_u16_node_is_free (l, i)) {
      alnls_u16_acquire_node_unsafe (l, i);
      break;
    }
  }
  return i;
}
/*---------------------------------------------------------------------------*/
BL_EXPORT void alnls_u16_insert_head (alnls_u16* l, alnls_u16_it n)
{
  bl_assert (alnls_u16_it_next (l, n) == alnls_u16_it_end (l));
  l->nodes[n] = l->head;
  l->head     = (u16) n;
  bl_assert (alnls_u16_it_begin (l) == n); /* oveflow check */
  ++l->size;
}
/*---------------------------------------------------------------------------*/
BL_EXPORT alnls_u16_it alnls_u16_drop_head (alnls_u16* l)
{
  if (alnls_u16_is_empty (l)) {
    return alnls_u16_it_end (l);
  }
  alnls_u16_it prev_head = alnls_u16_it_begin (l);
  l->head             = alnls_u16_it_next (l, prev_head);
  l->nodes[prev_head] = alnls_u16_it_end (l);
  --l->size;
  return prev_head;
}
/*---------------------------------------------------------------------------*/
