/* Autogenerated file, don't edit */
/* AUTOGENERATE: src/bl/base/alnls/array_linked_list_u8_basic.c */
/*---------------------------------------------------------------------------*/

#include <bl/base/impl/array_linked_list_u8.h>

BL_EXPORT void bl_alnls_u8_init_impl(
  bl_alnls_u8* l, bl_u8* nodes, bl_uword nodes_capacity
  )
{
  l->nodes    = nodes;
  l->capacity = nodes_capacity;
  l->head     = l->capacity;
  for (bl_alnls_u8_it it = 0; it < l->capacity; ++it) {
    bl_alnls_u8_node_release (l, it);
  }
  l->size = 0;
}
/*---------------------------------------------------------------------------*/
BL_EXPORT bl_alnls_u8_it
  bl_alnls_u8_try_acquire_node (bl_alnls_u8* l, bl_alnls_u8_it n)
{
  if (bl_alnls_u8_node_is_free (l, n)) {
    bl_alnls_u8_acquire_node_unsafe (l, n);
    return n;
  }
  return bl_alnls_u8_it_end (l);
}
/*---------------------------------------------------------------------------*/
BL_EXPORT bl_alnls_u8_it
  bl_alnls_u8_try_acquire_a_node (bl_alnls_u8* l)
{
  bl_alnls_u8_it i;
  for (i = 0; i < bl_alnls_u8_it_end (l); ++i) {
    if (bl_alnls_u8_node_is_free (l, i)) {
      bl_alnls_u8_acquire_node_unsafe (l, i);
      break;
    }
  }
  return i;
}
/*---------------------------------------------------------------------------*/
BL_EXPORT void
  bl_alnls_u8_insert_head (bl_alnls_u8* l, bl_alnls_u8_it n)
{
  bl_assert (bl_alnls_u8_it_next (l, n) == bl_alnls_u8_it_end (l));
  l->nodes[n] = l->head;
  l->head     = (bl_u8) n;
  bl_assert (bl_alnls_u8_it_begin (l) == n); /* oveflow check */
  ++l->size;
}
/*---------------------------------------------------------------------------*/
BL_EXPORT bl_alnls_u8_it
  bl_alnls_u8_drop_head (bl_alnls_u8* l)
{
  if (bl_alnls_u8_is_empty (l)) {
    return bl_alnls_u8_it_end (l);
  }
  bl_alnls_u8_it prev_head = bl_alnls_u8_it_begin (l);
  l->head             = bl_alnls_u8_it_next (l, prev_head);
  l->nodes[prev_head] = bl_alnls_u8_it_end (l);
  --l->size;
  return prev_head;
}
/*---------------------------------------------------------------------------*/
