/* Autogenerated file, don't edit */
/* AUTOGENERATE: include/bl/base/impl/array_linked_list_u64.h */
/*---------------------------------------------------------------------------*/
#ifndef __BL_ARRAY_LINKED_LIST_u64_H__
#define __BL_ARRAY_LINKED_LIST_u64_H__

#include <bl/base/assert.h>
#include <bl/base/libexport.h>
#include <bl/base/platform.h>
#include <bl/base/integer.h>
#include <bl/base/utility.h>

typedef u64 alnls_u64_it;
/*---------------------------------------------------------------------------*/
typedef struct alnls_u64 {
  uword head;
  uword capacity;
  uword size;
  u64* nodes;
}
alnls_u64;
/*---------------------------------------------------------------------------*/
#define alnls_u64_foreach(type_ptr, it_var)\
  for (alnls_u64_it alnls_u64_priv_curr_it = alnls_u64_it_begin ((type_ptr)),\
         it_var = alnls_u64_priv_curr_it;\
       alnls_u64_it_in_range ((type_ptr), alnls_u64_priv_curr_it) &&\
         (alnls_u64_priv_curr_it =\
            alnls_u64_it_next ((type_ptr), alnls_u64_priv_curr_it), 1);\
       it_var = alnls_u64_priv_curr_it\
       )
/*---------------------------------------------------------------------------*/
#define alnls_u64_foreach_read_only(type_ptr, it_var)\
  for (it_var = alnls_u64_it_begin ((type_ptr));\
       alnls_u64_it_in_range ((type_ptr), it_var);\
       it_var = alnls_u64_it_next ((type_ptr), it_var)\
       )
/*---------------------------------------------------------------------------*/
#define alnls_u64_init(list, backing_nodes_array)\
  alnls_u64_init_impl(\
    (list),\
    (backing_nodes_array),\
    arr_elems (backing_nodes_array)\
    )
/*---------------------------------------------------------------------------*/
static inline alnls_u64_it alnls_u64_it_end (alnls_u64* l)
{
  return l->capacity;
}
/*---------------------------------------------------------------------------*/
static inline alnls_u64_it alnls_u64_it_begin (alnls_u64* l)
{
  return l->head;
}
/*---------------------------------------------------------------------------*/
static inline alnls_u64_it alnls_u64_capacity (alnls_u64* l)
{
  return l->capacity;
}
/*---------------------------------------------------------------------------*/
static inline alnls_u64_it alnls_u64_size (alnls_u64* l)
{
  return l->size;
}
/*---------------------------------------------------------------------------*/
static inline alnls_u64_it alnls_u64_it_in_range (alnls_u64* l, alnls_u64_it it)
{
  return it < l->capacity;
}
/*---------------------------------------------------------------------------*/
static inline bool alnls_u64_is_empty (alnls_u64* l)
{
  return alnls_u64_it_begin (l) == alnls_u64_it_end (l);
}
/*---------------------------------------------------------------------------*/
static inline alnls_u64_it alnls_u64_it_next (alnls_u64* l, alnls_u64_it it)
{
  return l->nodes[it];
}
/*---------------------------------------------------------------------------*/
static inline void alnls_u64_node_release (alnls_u64* l, alnls_u64_it it)
{
  l->nodes[it] = it;
}
/*---------------------------------------------------------------------------*/
static inline bool alnls_u64_node_is_free (alnls_u64* l, alnls_u64_it it)
{
  return l->nodes[it] == it;
}
/*---------------------------------------------------------------------------*/
static inline void alnls_u64_acquire_node_unsafe (alnls_u64* l, alnls_u64_it it)
{
  bl_assert (it < alnls_u64_capacity (l));
  bl_assert (alnls_u64_node_is_free (l, it));
  l->nodes[it] = alnls_u64_it_end (l);
}
/*---------------------------------------------------------------------------*/
extern BL_EXPORT void alnls_u64_init_impl(
  alnls_u64* l, u64* nodes, uword nodes_capacity
  );
/*---------------------------------------------------------------------------*/
extern BL_EXPORT alnls_u64_it alnls_u64_try_acquire_node (alnls_u64* l, alnls_u64_it n);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT alnls_u64_it alnls_u64_try_acquire_a_node (alnls_u64* l);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT void alnls_u64_insert_head (alnls_u64* l, alnls_u64_it n);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT alnls_u64_it alnls_u64_drop_head (alnls_u64* l);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT void alnls_u64_insert_tail (alnls_u64* l, alnls_u64_it n);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT alnls_u64_it alnls_u64_drop (alnls_u64* l, alnls_u64_it n);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT alnls_u64_it alnls_u64_drop_tail (alnls_u64* l);

#endif /* #define __BL_ARRAY_LINKED_LIST_u64_H__ */

/*---------------------------------------------------------------------------*/
