/* Autogenerated file, don't edit */
/* AUTOGENERATE: include/bl/base/impl/array_linked_list_u16.h */
/*---------------------------------------------------------------------------*/
#ifndef __BL_ARRAY_LINKED_LIST_u16_H__
#define __BL_ARRAY_LINKED_LIST_u16_H__

#include <bl/base/assert.h>
#include <bl/base/libexport.h>
#include <bl/base/platform.h>
#include <bl/base/integer.h>
#include <bl/base/utility.h>

typedef bl_u16 bl_alnls_u16_it;
/*---------------------------------------------------------------------------*/
typedef struct bl_alnls_u16 {
  bl_uword capacity;
  bl_uword size;
  bl_u16  head;
  bl_u16* nodes;
}
bl_alnls_u16;
/*---------------------------------------------------------------------------*/
#define bl_alnls_u16_foreach(type_ptr, it_var)\
  for(\
    bl_alnls_u16_it bl_alnls_u16_priv_curr_it =\
        bl_alnls_u16_it_begin ((type_ptr)),\
      it_var = bl_alnls_u16_priv_curr_it;\
    bl_alnls_u16_it_in_range ((type_ptr), bl_alnls_u16_priv_curr_it) &&\
      (bl_alnls_u16_priv_curr_it =\
        bl_alnls_u16_it_next ((type_ptr), bl_alnls_u16_priv_curr_it), 1);\
    it_var = bl_alnls_u16_priv_curr_it\
    )
/*---------------------------------------------------------------------------*/
#define bl_alnls_u16_foreach_read_only(type_ptr, it_var)\
  for(\
    it_var = bl_alnls_u16_it_begin ((type_ptr));\
    bl_alnls_u16_it_in_range ((type_ptr), it_var);\
    it_var = bl_alnls_u16_it_next ((type_ptr), it_var)\
    )
/*---------------------------------------------------------------------------*/
#define bl_alnls_u16_init(list, backing_nodes_array)\
  bl_alnls_u16_init_impl(\
    (list),\
    (backing_nodes_array),\
    bl_arr_elems (backing_nodes_array)\
    )
/*---------------------------------------------------------------------------*/
static inline bl_alnls_u16_it bl_alnls_u16_it_end (bl_alnls_u16* l)
{
  return l->capacity;
}
/*---------------------------------------------------------------------------*/
static inline bl_alnls_u16_it bl_alnls_u16_it_begin (bl_alnls_u16* l)
{
  return l->head;
}
/*---------------------------------------------------------------------------*/
static inline bl_alnls_u16_it bl_alnls_u16_capacity (bl_alnls_u16* l)
{
  return l->capacity;
}
/*---------------------------------------------------------------------------*/
static inline bl_alnls_u16_it bl_alnls_u16_size (bl_alnls_u16* l)
{
  return l->size;
}
/*---------------------------------------------------------------------------*/
static inline bl_alnls_u16_it
  bl_alnls_u16_it_in_range (bl_alnls_u16* l, bl_alnls_u16_it it)
{
  return it < l->capacity;
}
/*---------------------------------------------------------------------------*/
static inline bool bl_alnls_u16_is_empty (bl_alnls_u16* l)
{
  return bl_alnls_u16_it_begin (l) == bl_alnls_u16_it_end (l);
}
/*---------------------------------------------------------------------------*/
static inline bl_alnls_u16_it
  bl_alnls_u16_it_next (bl_alnls_u16* l, bl_alnls_u16_it it)
{
  return l->nodes[it];
}
/*---------------------------------------------------------------------------*/
static inline void
  bl_alnls_u16_node_release (bl_alnls_u16* l, bl_alnls_u16_it it)
{
  l->nodes[it] = it;
}
/*---------------------------------------------------------------------------*/
static inline bool
  bl_alnls_u16_node_is_free (bl_alnls_u16* l, bl_alnls_u16_it it)
{
  return l->nodes[it] == it;
}
/*---------------------------------------------------------------------------*/
static inline void bl_alnls_u16_acquire_node_unsafe(
  bl_alnls_u16* l, bl_alnls_u16_it it
  )
{
  bl_assert (it < bl_alnls_u16_capacity (l));
  bl_assert (bl_alnls_u16_node_is_free (l, it));
  l->nodes[it] = bl_alnls_u16_it_end (l);
}
/*---------------------------------------------------------------------------*/
extern BL_EXPORT void bl_alnls_u16_init_impl(
  bl_alnls_u16* l, bl_u16* nodes, bl_uword nodes_capacity
  );
/*---------------------------------------------------------------------------*/
extern BL_EXPORT bl_alnls_u16_it
  bl_alnls_u16_try_acquire_node (bl_alnls_u16* l, bl_alnls_u16_it n);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT bl_alnls_u16_it
  bl_alnls_u16_try_acquire_a_node (bl_alnls_u16* l);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT void
  bl_alnls_u16_insert_head (bl_alnls_u16* l, bl_alnls_u16_it n);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT bl_alnls_u16_it
  bl_alnls_u16_drop_head (bl_alnls_u16* l);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT void
  bl_alnls_u16_insert_tail (bl_alnls_u16* l, bl_alnls_u16_it n);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT bl_alnls_u16_it
  bl_alnls_u16_drop (bl_alnls_u16* l, bl_alnls_u16_it n);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT bl_alnls_u16_it
  bl_alnls_u16_drop_tail (bl_alnls_u16* l);

#endif /* #define __BL_ARRAY_LINKED_LIST_u16_H__ */

/*---------------------------------------------------------------------------*/
