/* Autogenerated file, don't edit */
/* AUTOGENERATE: include/bl/base/impl/array_doubly_linked_list_u32.h */
/*---------------------------------------------------------------------------*/
#ifndef __BL_ARRAY_DOUBLY_LINKED_LIST_u32_H__
#define __BL_ARRAY_DOUBLY_LINKED_LIST_u32_H__

/* SELF-COMMENT: why not save code size and make the head the first element of
   "nodes" */

#include <bl/base/assert.h>
#include <bl/base/libexport.h>
#include <bl/base/platform.h>
#include <bl/base/integer.h>
#include <bl/base/utility.h>

typedef u32 adlnls_u32_it;
/*---------------------------------------------------------------------------*/
typedef struct adlnls_u32_hook {
  u32 next : type_bits (u32) / 2;
  u32 prev : type_bits (u32) / 2;
}
adlnls_u32_hook;
/*---------------------------------------------------------------------------*/
typedef struct adlnls_u32 {
  adlnls_u32_hook head;
  adlnls_u32_hook* nodes;
  uword capacity;
  uword size;
}
adlnls_u32;
/*---------------------------------------------------------------------------*/
#define adlnls_u32_foreach(type_ptr, it_var)\
  for (adlnls_u32_it adlnls_u32_priv_curr_it = adlnls_u32_it_begin ((type_ptr)),\
         it_var = adlnls_u32_priv_curr_it;\
       adlnls_u32_it_in_range ((type_ptr), adlnls_u32_priv_curr_it) &&\
         (adlnls_u32_priv_curr_it =\
            adlnls_u32_it_next ((type_ptr), adlnls_u32_priv_curr_it), 1);\
       it_var = adlnls_u32_priv_curr_it\
       )
/*---------------------------------------------------------------------------*/
#define adlnls_u32_foreach_read_only(type_ptr, it_var)\
  for (it_var = adlnls_u32_it_begin ((type_ptr));\
       adlnls_u32_it_in_range ((type_ptr), it_var);\
       it_var = adlnls_u32_it_next ((type_ptr), it_var)\
       )
/*---------------------------------------------------------------------------*/
#define adlnls_u32_foreach_r(type_ptr, it_var)\
  for (adlnls_u32_it adlnls_u32_priv_curr_it = adlnls_u32_it_rbegin ((type_ptr)),\
         it_var = adlnls_u32_priv_curr_it;\
       adlnls_u32_it_in_range_r ((type_ptr), adlnls_u32_priv_curr_it) &&\
         (adlnls_u32_priv_curr_it =\
            adlnls_u32_it_prev ((type_ptr), adlnls_u32_priv_curr_it), 1);\
       it_var = adlnls_u32_priv_curr_it\
       )
/*---------------------------------------------------------------------------*/
#define adlnls_u32_foreach_r_read_only(type_ptr, it_var)\
  for (it_var = adlnls_u32_it_rbegin ((type_ptr));\
       adlnls_u32_it_in_range_r ((type_ptr), it_var);\
       it_var = adlnls_u32_it_prev ((type_ptr), it_var)\
       )
/*---------------------------------------------------------------------------*/
#define adlnls_u32_init(list, backing_nodes_array)\
  adlnls_u32_init_impl(\
    (list),\
    (backing_nodes_array),\
    arr_elems (backing_nodes_array)\
    )
/*---------------------------------------------------------------------------*/
static inline adlnls_u32_it adlnls_u32_it_end (adlnls_u32* l)
{
  return l->capacity;
}
/*---------------------------------------------------------------------------*/
static inline adlnls_u32_it adlnls_u32_it_rend (adlnls_u32* l)
{
  return l->capacity;
}
/*---------------------------------------------------------------------------*/
static inline adlnls_u32_it adlnls_u32_it_begin (adlnls_u32* l)
{
  return l->head.next;
}
/*---------------------------------------------------------------------------*/
static inline adlnls_u32_it adlnls_u32_it_rbegin (adlnls_u32* l)
{
  return l->head.prev;
}
/*---------------------------------------------------------------------------*/
static inline adlnls_u32_it adlnls_u32_capacity (adlnls_u32* l)
{
  return l->capacity;
}
/*---------------------------------------------------------------------------*/
static inline adlnls_u32_it adlnls_u32_size (adlnls_u32* l)
{
  return l->size;
}
/*---------------------------------------------------------------------------*/
static inline adlnls_u32_it adlnls_u32_it_in_range (adlnls_u32* l, adlnls_u32_it it)
{
  return it < l->capacity;
}
/*---------------------------------------------------------------------------*/
static inline adlnls_u32_it adlnls_u32_it_in_range_r (adlnls_u32* l, adlnls_u32_it it)
{
  return it < l->capacity;
}
/*---------------------------------------------------------------------------*/
static inline bool adlnls_u32_is_empty (adlnls_u32* l)
{
  return adlnls_u32_it_begin (l) == adlnls_u32_it_end (l);
}
/*---------------------------------------------------------------------------*/
static inline adlnls_u32_it adlnls_u32_it_next (adlnls_u32* l, adlnls_u32_it it)
{
  return l->nodes[it].next;
}
/*---------------------------------------------------------------------------*/
static inline adlnls_u32_it adlnls_u32_it_prev (adlnls_u32* l, adlnls_u32_it it)
{
  return l->nodes[it].prev;
}
/*---------------------------------------------------------------------------*/
static inline void adlnls_u32_node_release (adlnls_u32* l, adlnls_u32_it it)
{
  l->nodes[it].next = it;
  l->nodes[it].prev = it;
}
/*---------------------------------------------------------------------------*/
static inline bool adlnls_u32_node_is_free (adlnls_u32* l, adlnls_u32_it it)
{
  return l->nodes[it].next == it;
}
/*---------------------------------------------------------------------------*/
static inline void adlnls_u32_acquire_node_unsafe (adlnls_u32* l, adlnls_u32_it it)
{
  bl_assert (it < adlnls_u32_capacity (l));
  bl_assert (adlnls_u32_node_is_free (l, it));
  l->nodes[it].prev = adlnls_u32_it_end (l);
  l->nodes[it].next = adlnls_u32_it_end (l);
}
/*---------------------------------------------------------------------------*/
extern BL_EXPORT void adlnls_u32_init_impl(
  adlnls_u32* l, u32* nodes, uword nodes_capacity
  );
/*---------------------------------------------------------------------------*/
extern BL_EXPORT adlnls_u32_it adlnls_u32_try_acquire_node (adlnls_u32* l, adlnls_u32_it n);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT adlnls_u32_it adlnls_u32_try_acquire_a_node (adlnls_u32* l);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT void adlnls_u32_insert_head (adlnls_u32* l, adlnls_u32_it n);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT void adlnls_u32_insert_tail (adlnls_u32* l, adlnls_u32_it n);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT adlnls_u32_it adlnls_u32_drop_head (adlnls_u32* l);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT adlnls_u32_it adlnls_u32_drop_tail (adlnls_u32* l);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT adlnls_u32_it adlnls_u32_drop (adlnls_u32* l, adlnls_u32_it n);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT adlnls_u32_it adlnls_u32_drop_explicit(
  adlnls_u32* l, adlnls_u32_it n, bool return_previous
  );

#endif /* #define __BL_ARRAY_LINKED_LIST_u32_H__ */

/*---------------------------------------------------------------------------*/
