/* Autogenerated file, don't edit */
/* AUTOGENERATE: include/bl/base/impl/array_doubly_linked_list_u8.h */
/*---------------------------------------------------------------------------*/
#ifndef __BL_ARRAY_DOUBLY_LINKED_LIST_u8_H__
#define __BL_ARRAY_DOUBLY_LINKED_LIST_u8_H__

/* SELF-COMMENT: why not save code size and make the head the first element of
   "nodes" */

#include <bl/base/assert.h>
#include <bl/base/libexport.h>
#include <bl/base/platform.h>
#include <bl/base/integer.h>
#include <bl/base/utility.h>

typedef u8 adlnls_u8_it;
/*---------------------------------------------------------------------------*/
typedef struct adlnls_u8_hook {
  u8 next : type_bits (u8) / 2;
  u8 prev : type_bits (u8) / 2;
}
adlnls_u8_hook;
/*---------------------------------------------------------------------------*/
typedef struct adlnls_u8 {
  adlnls_u8_hook head;
  adlnls_u8_hook* nodes;
  uword capacity;
  uword size;
}
adlnls_u8;
/*---------------------------------------------------------------------------*/
#define adlnls_u8_foreach(type_ptr, it_var)\
  for (adlnls_u8_it adlnls_u8_priv_curr_it = adlnls_u8_it_begin ((type_ptr)),\
         it_var = adlnls_u8_priv_curr_it;\
       adlnls_u8_it_in_range ((type_ptr), adlnls_u8_priv_curr_it) &&\
         (adlnls_u8_priv_curr_it =\
            adlnls_u8_it_next ((type_ptr), adlnls_u8_priv_curr_it), 1);\
       it_var = adlnls_u8_priv_curr_it\
       )
/*---------------------------------------------------------------------------*/
#define adlnls_u8_foreach_read_only(type_ptr, it_var)\
  for (it_var = adlnls_u8_it_begin ((type_ptr));\
       adlnls_u8_it_in_range ((type_ptr), it_var);\
       it_var = adlnls_u8_it_next ((type_ptr), it_var)\
       )
/*---------------------------------------------------------------------------*/
#define adlnls_u8_foreach_r(type_ptr, it_var)\
  for (adlnls_u8_it adlnls_u8_priv_curr_it = adlnls_u8_it_rbegin ((type_ptr)),\
         it_var = adlnls_u8_priv_curr_it;\
       adlnls_u8_it_in_range_r ((type_ptr), adlnls_u8_priv_curr_it) &&\
         (adlnls_u8_priv_curr_it =\
            adlnls_u8_it_prev ((type_ptr), adlnls_u8_priv_curr_it), 1);\
       it_var = adlnls_u8_priv_curr_it\
       )
/*---------------------------------------------------------------------------*/
#define adlnls_u8_foreach_r_read_only(type_ptr, it_var)\
  for (it_var = adlnls_u8_it_rbegin ((type_ptr));\
       adlnls_u8_it_in_range_r ((type_ptr), it_var);\
       it_var = adlnls_u8_it_prev ((type_ptr), it_var)\
       )
/*---------------------------------------------------------------------------*/
#define adlnls_u8_init(list, backing_nodes_array)\
  adlnls_u8_init_impl(\
    (list),\
    (backing_nodes_array),\
    arr_elems (backing_nodes_array)\
    )
/*---------------------------------------------------------------------------*/
static inline adlnls_u8_it adlnls_u8_it_end (adlnls_u8* l)
{
  return l->capacity;
}
/*---------------------------------------------------------------------------*/
static inline adlnls_u8_it adlnls_u8_it_rend (adlnls_u8* l)
{
  return l->capacity;
}
/*---------------------------------------------------------------------------*/
static inline adlnls_u8_it adlnls_u8_it_begin (adlnls_u8* l)
{
  return l->head.next;
}
/*---------------------------------------------------------------------------*/
static inline adlnls_u8_it adlnls_u8_it_rbegin (adlnls_u8* l)
{
  return l->head.prev;
}
/*---------------------------------------------------------------------------*/
static inline adlnls_u8_it adlnls_u8_capacity (adlnls_u8* l)
{
  return l->capacity;
}
/*---------------------------------------------------------------------------*/
static inline adlnls_u8_it adlnls_u8_size (adlnls_u8* l)
{
  return l->size;
}
/*---------------------------------------------------------------------------*/
static inline adlnls_u8_it adlnls_u8_it_in_range (adlnls_u8* l, adlnls_u8_it it)
{
  return it < l->capacity;
}
/*---------------------------------------------------------------------------*/
static inline adlnls_u8_it adlnls_u8_it_in_range_r (adlnls_u8* l, adlnls_u8_it it)
{
  return it < l->capacity;
}
/*---------------------------------------------------------------------------*/
static inline bool adlnls_u8_is_empty (adlnls_u8* l)
{
  return adlnls_u8_it_begin (l) == adlnls_u8_it_end (l);
}
/*---------------------------------------------------------------------------*/
static inline adlnls_u8_it adlnls_u8_it_next (adlnls_u8* l, adlnls_u8_it it)
{
  return l->nodes[it].next;
}
/*---------------------------------------------------------------------------*/
static inline adlnls_u8_it adlnls_u8_it_prev (adlnls_u8* l, adlnls_u8_it it)
{
  return l->nodes[it].prev;
}
/*---------------------------------------------------------------------------*/
static inline void adlnls_u8_node_release (adlnls_u8* l, adlnls_u8_it it)
{
  l->nodes[it].next = it;
  l->nodes[it].prev = it;
}
/*---------------------------------------------------------------------------*/
static inline bool adlnls_u8_node_is_free (adlnls_u8* l, adlnls_u8_it it)
{
  return l->nodes[it].next == it;
}
/*---------------------------------------------------------------------------*/
static inline void adlnls_u8_acquire_node_unsafe (adlnls_u8* l, adlnls_u8_it it)
{
  bl_assert (it < adlnls_u8_capacity (l));
  bl_assert (adlnls_u8_node_is_free (l, it));
  l->nodes[it].prev = adlnls_u8_it_end (l);
  l->nodes[it].next = adlnls_u8_it_end (l);
}
/*---------------------------------------------------------------------------*/
extern BL_EXPORT void adlnls_u8_init_impl(
  adlnls_u8* l, u8* nodes, uword nodes_capacity
  );
/*---------------------------------------------------------------------------*/
extern BL_EXPORT adlnls_u8_it adlnls_u8_try_acquire_node (adlnls_u8* l, adlnls_u8_it n);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT adlnls_u8_it adlnls_u8_try_acquire_a_node (adlnls_u8* l);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT void adlnls_u8_insert_head (adlnls_u8* l, adlnls_u8_it n);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT void adlnls_u8_insert_tail (adlnls_u8* l, adlnls_u8_it n);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT adlnls_u8_it adlnls_u8_drop_head (adlnls_u8* l);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT adlnls_u8_it adlnls_u8_drop_tail (adlnls_u8* l);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT adlnls_u8_it adlnls_u8_drop (adlnls_u8* l, adlnls_u8_it n);
/*---------------------------------------------------------------------------*/
extern BL_EXPORT adlnls_u8_it adlnls_u8_drop_explicit(
  adlnls_u8* l, adlnls_u8_it n, bool return_previous
  );

#endif /* #define __BL_ARRAY_LINKED_LIST_u8_H__ */

/*---------------------------------------------------------------------------*/
